services:
  db:
    image: postgres:15
    container_name: budget_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: budget_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data: