"""add category relationship

Revision ID: 54cd465d3350
Revises: dc31b993db3c
Create Date: 2026-05-07 12:15:00.570343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cd465d3350'
down_revision: Union[str, Sequence[str], None] = 'dc31b993db3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.add_column('transactions', sa.Column('memo', sa.String(), nullable=True))
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_column('transactions', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('transactions', 'memo')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
