"""add category and fk

Revision ID: dc31b993db3c
Revises: c84952de47ed
Create Date: 2026-05-06 13:00:56.093534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc31b993db3c'
down_revision: Union[str, Sequence[str], None] = 'c84952de47ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('transactions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(
        'transactions',
        'date',
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        postgresql_using="date::date")
    op.create_index('ix_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_date', 'transactions', ['date'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.drop_index('ix_transactions_category_id', table_name='transactions')
    op.alter_column('transactions', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    op.drop_table('categories')
    # ### end Alembic commands ###
