"""add date to transactions

Revision ID: eb5c1c92c8dc
Revises: 407319e2caee
Create Date: 2026-08-09 17:34:59.480337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5c1c92c8dc'
down_revision: Union[str, Sequence[str], None] = '407319e2caee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
